export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_LOGINOUT = "USER_LOGIN_LOGINOUT";

export const USER_ADDRESS_REQUEST = "USER_ADDRESS_REQUEST";
export const USER_ADDRESS_SUCCESS = "USER_ADDRESS_SUCCESS";
export const USER_ADDRESS_FAIL = "USER_ADDRESSFAIL";

export const USER_CART_REQUEST = "USER_CART_REQUEST";
export const USER_CART_SUCCESS = "USER_CART_SUCCESS";
export const USER_CART_FAIL = "USER_CART_FAIL";

export const USER_ORDERCART_REQUEST = "USER_ORDERCART_REQUEST";
export const USER_ORDERCART_SUCCESS = "USER_ORDERCART_SUCCESS";
export const USER_ORDERCART_FAIL = "USER_ORDERCART_FAIL";